[project]
name = "mission-planner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "flask==3.1.1",
    "magic-wormhole==0.20.0",
    "python-dotenv==1.1.1",
]
